services:

    E7\FeatureFlagsBundle\Feature\FeatureBox:
        arguments:
            - !tagged e7.feature_flag

    feature_flags:
        public: true
        alias: E7\FeatureFlagsBundle\Feature\FeatureBox

    E7\FeatureFlagsBundle\Twig\FeatureExtension:
        tags:
            - { name: twig.extension }
