services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    E7\FeatureFlagsBundle\Context\Context:
        public: true

    E7\FeatureFlagsBundle\Feature\FeatureBoxBuilder:
        public: true

    E7\FeatureFlagsBundle\Feature\FeatureBox:
        public: true
        factory: ['@E7\FeatureFlagsBundle\Feature\FeatureBoxBuilder', 'buildFromConfig']
        arguments:
            $config: '%e7_feature_flags%'

    E7\FeatureFlagsBundle\Feature\Conditions\ConditionFactory:

    # commands
    E7\FeatureFlagsBundle\Command\DebugFeatureCommand:
        public: true
        arguments:
            - '@E7\FeatureFlagsBundle\Feature\FeatureBox'
        tags:
            - { name: 'console.command', command: 'ebene7:feature_flags:debug' } 

    E7\FeatureFlagsBundle\Command\ListFeaturesCommand:
        public: true
        arguments:
            - '@E7\FeatureFlagsBundle\Feature\FeatureBox'
        tags:
            - { name: 'console.command', command: 'ebene7:feature_flags:list', alias: 'Bammm' }

    # Twig
    E7\FeatureFlagsBundle\Twig\FeatureExtension:
        arguments:
            - '@E7\FeatureFlagsBundle\Feature\FeatureBox'
        tags:
            - { name: twig.extension }
