services:

    # commands
    E7\FeatureFlagsBundle\Command\ListFeaturesCommand:
        public: true
        arguments:
            - '@E7\FeatureFlagsBundle\Feature\FeatureBox'
        tags:
            - { name: 'console.command', command: 'ebene7:feature_flags:list' }

    E7\FeatureFlagsBundle\Command\DebugFeatureCommand:
        public: true
        arguments:
            - '@E7\FeatureFlagsBundle\Feature\FeatureBox'
        tags:
            - { name: 'console.command', command: 'ebene7:feature_flags:debug' }        

    E7\FeatureFlagsBundle\Context\Context:
        public: true

    E7\FeatureFlagsBundle\Feature\FeatureBoxBuilder:
        public: true
        arguments:
            $container: '@service_container'

    E7\FeatureFlagsBundle\Feature\FeatureBox:
        public: true
        factory: ['@E7\FeatureFlagsBundle\Feature\FeatureBoxBuilder', 'buildFromConfig']
#        arguments:
#            - !tagged e7.feature_flag,
#            - '@E7\FeatureFlagsBundle\Context\Context'
#
#    e7_feature_context:
#        alias: E7\FeatureFlagsBundle\Feature\FeatureBox
#        public: true

#    e7_feature_flags:
#        alias: E7\FeatureFlagsBundle\Feature\FeatureBox
#        public: true

    # Twig
    E7\FeatureFlagsBundle\Twig\FeatureExtension:
        arguments:
            - '@E7\FeatureFlagsBundle\Feature\FeatureBox'
        tags:
            - { name: twig.extension }
