services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    E7\FeatureFlagsBundle\Context\Context:
        public: true

    E7\FeatureFlagsBundle\Feature\FeatureBoxBuilder:
        arguments:
            $profile: '@E7\FeatureFlagsBundle\Profiler\Profile'
        public: true

    E7\FeatureFlagsBundle\Feature\FeatureBox:
        public: true
        factory: ['@E7\FeatureFlagsBundle\Feature\FeatureBoxBuilder', 'buildFromConfig']
        arguments:
            $config: '%e7_feature_flags%'

    E7\FeatureFlagsBundle\Feature\Conditions\TypeResolver:
        public: true

    E7\FeatureFlagsBundle\Feature\Conditions\ConditionFactory:
        $typeResolver: '@E7\FeatureFlagsBundle\Feature\Conditions\TypeResolver'

    # commands
    E7\FeatureFlagsBundle\Command\DebugFeatureCommand:
        public: true
        arguments:
            - '@E7\FeatureFlagsBundle\Feature\FeatureBox'
        tags:
            - { name: 'console.command', command: 'debug:feature-flags' }
            - { name: 'console.command', command: 'ebene7:feature_flags:debug' }

    E7\FeatureFlagsBundle\Command\ListFeaturesCommand:
        public: true
        arguments:
            - '@E7\FeatureFlagsBundle\Feature\FeatureBox'
        tags:
            - { name: 'console.command', command: 'ebene7:feature_flags:list', alias: 'Bammm' }

    # Profiler
    E7\FeatureFlagsBundle\DataCollector\FeatureCollector:
        arguments:
            - '@E7\FeatureFlagsBundle\Feature\FeatureBox'
        tags:
            -
                name:     data_collector
                template: '@E7FeatureFlags/data_collector/feature.html.twig'
                id:       'feature-flags'
        public: false

    E7\FeatureFlagsBundle\Profiler\Profile:

    # Twig
    E7\FeatureFlagsBundle\Twig\FeatureExtension:
        arguments:
            - '@E7\FeatureFlagsBundle\Feature\FeatureBox'
        tags:
            - { name: twig.extension }
