services:
    _defaults:
        autowire: true
        autoconfigure: true

    E7\FeatureFlagsBundle\Context\Context:

    e7_feature_context:
        alias: E7\FeatureFlagsBundle\Feature\FeatureBox
        public: true

    E7\FeatureFlagsBundle\Feature\FeatureBox:
        arguments:
            - !tagged e7.feature_flag

    e7_feature_flags:
        alias: E7\FeatureFlagsBundle\Feature\FeatureBox
        public: true

    # Twig
    E7\FeatureFlagsBundle\Twig\FeatureExtension:
        arguments:
            - '@e7_feature_flags'
        tags:
            - { name: twig.extension }
