services:
    
    E7\FeatureFlagsBundle\Feature\FeatureBox:
        public: true
        alias: 'feature_flags'
    
    E7\FeatureFlagsBundle\Twig\FeatureExtension:
        tags:
            - { name: twig.extension }